# Site settings
title: Fibaro Training Portal
description: >
  Welcome to the FIBARO ANZ Trade Portal for authorised resellers

# file paths
url:     "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
img:     "/_assets/img"
css:     "/_assets/css"
js:      "/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed